

# Process title
title="mailcast"
processes=2

# Can be overriden in the UI by admin
appname="Mailcast"

[process]
# @include "user.toml"

[www]
secret="secret cat"
postsize="5MB"
host=false # local ip address to bind to
port=3002
proxy=false # set to true if using CloudFlare etc or behind Nginx/Apache
secure=false # if true uses secure cookies
#baseUrl=false # set to default application url, can be overriden in web interface

[log]
level="silly"
www=':remote-addr [:date[iso]] :site-user ":method :url HTTP/:http-version" :status :res[content-length]'

[dbs]
# @include "dbs.toml"

[mta]
# Load MTA config
# @include "mta/minimta.toml"

[verp]
# Load VERP MX config
# @include "verp.toml"

[upgrade]
checkInterval=3600 # seconds
